---

- name: Install redis server
  apt:
    update_cache: yes
    name: redis-server
    state: present

- name: Configure redis
  template:
    src: redis.conf.j2
    dest: "{{ redis_conf_path }}"
    mode: 0644
  notify: restart redis

- name: Ensure redis is running and enabled on boot
  service: "name={{ redis_daemon }} state=started enabled=yes"
  